apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.name" . }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ default 5000 .Values.service.targetPort }}
          readinessProbe:
          {{-  toYaml .Values.readinessProbe | nindent 12 }}

          livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}

          resources:
          {{- toYaml .Values.resources | nindent 12 }}

          env:
            - name: {{ .Values.envName }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: {{ .Values.configMapKey }}
