apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: python-app-shivam-shah:latest
          imagePullPolicy: IfNotPresent
          command: ["flask", "run", "--host=0.0.0.0"]
          ports:
            - containerPort: 5000
          env:
            - name: ES_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: ELASTICSEARCH_URL