# apiVersion: v1
# kind: Service
# metadata:
#   name: flask-app-service
# spec:
#   selector:
#     app: flask-app
#   ports:
#     - name: http
#       port: 5000
#       targetPort: 5000
#   type: ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ default 8080 .Values.service.targetPort }}
      name: {{ default "http" .Values.service.portName }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}